#bind-key b command-prompt "select-pane -t :.+"
bind-key C-b run "tmux select-pane -t :.+"
# 将分割窗格切换快捷键更改为Ctrl-b + h/j/k/l
unbind Left
unbind Down
unbind Up
unbind Right

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# 解决tmux中vim ESC键有延迟的问题
set -sg escape-time 10
